name: Bug Report
description: TNT TAGプラグインのバグを報告
title: "[Bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        TNT TAGプラグインのバグ報告をありがとうございます。
        問題を迅速に解決するため、以下の情報をご提供ください。

  - type: textarea
    id: description
    attributes:
      label: バグの説明
      description: 発生した問題について詳しく説明してください
      placeholder: どのような問題が発生しましたか？
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: バグを再現するための手順を記載してください
      placeholder: |
        1. '...'コマンドを実行
        2. '...'をクリック
        3. エラーが発生
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 本来どのように動作すべきでしたか？
      placeholder: 期待していた動作を説明してください
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
      description: 実際にどのような動作をしましたか？
      placeholder: 実際に起こった動作を説明してください
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 重要度
      description: このバグの重要度を選択してください
      options:
        - Critical（ゲームが開始できない、クラッシュする等）
        - High（主要機能が動作しない）
        - Medium（一部機能に問題がある）
        - Low（軽微な問題、表示の不具合等）
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: プラグインバージョン
      description: 使用しているTNT TAGのバージョンを入力してください
      placeholder: 例) 1.0.0
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: サーバーバージョン
      description: 使用しているMinecraftサーバーのバージョンを入力してください
      placeholder: 例) Paper 1.21.10
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Javaバージョン
      description: 使用しているJavaのバージョンを入力してください
      placeholder: 例) Java 21
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: ログ・エラーメッセージ
      description: 関連するログやエラーメッセージがあれば貼り付けてください
      placeholder: |
        ```
        ここにログを貼り付けてください
        ```
      render: shell

  - type: textarea
    id: config
    attributes:
      label: 設定ファイル
      description: 問題に関連する可能性のある設定があれば記載してください
      placeholder: |
        ```yaml
        config.ymlの関連部分を貼り付けてください
        ```
      render: yaml

  - type: input
    id: players
    attributes:
      label: プレイヤー数
      description: バグ発生時のプレイヤー数を入力してください
      placeholder: 例) 20人
    validations:
      required: false

  - type: dropdown
    id: game-phase
    attributes:
      label: 発生タイミング
      description: どのフェーズでバグが発生しましたか？
      options:
        - ゲーム開始前（待機中）
        - ゲーム開始時
        - ラウンド中
        - ラウンド終了時
        - ゲーム終了時
        - その他
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 追加情報
      description: その他、問題解決に役立つ情報があれば記載してください
      placeholder: スクリーンショット、動画、他のプラグインとの干渉など

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認事項
      description: 以下を確認してください
      options:
        - label: 最新バージョンのプラグインを使用しています
          required: false
        - label: 既存のissueに同じ問題が報告されていないことを確認しました
          required: true
        - label: ログやエラーメッセージに個人情報が含まれていないことを確認しました
          required: true
